### ISSUE TITLE
The Iphone mirroring App boots but it still checks country code once it is connected the phone and blocks

### ISSUE THREAD

**Issue by seveneves** [zer0belisk/Iphonemirroring#1]
After running the script the app does open on MacOS Sequoia. It detects the phone and then shows a similar error that country is not supported.

<img width="395" alt="image" src="https://github.com/user-attachments/assets/4813a01b-6f2f-4612-8140-e6ca5e00f802">

**Comment by zer0belisk** [comment]
in the guide it's written that you are supposed to change the country in the app store app to the US account first
