### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by PeciUno** [zer0belisk/Iphonemirroring#2]
<img width="592" alt="image" src="https://github.com/user-attachments/assets/2c3088f5-43d7-4ddd-8e61-61ed3173df79">
I get the same message saying that this function is not available in my country.

I have already changed my country within the appstore on my iPhone.

**Comment by zer0belisk** [comment]
sudo...

**Comment by PeciUno** [comment]
I have tried both using sudo and without using it and the answer is the same

<img width="564" alt="image" src="https://github.com/user-attachments/assets/d4143864-befd-461b-b248-4475cb4a5585">
